### PR TITLE
minor cleanup

### PR DESCRIPTION
**Pull request by valkyrienyanko**

### CODE REVIEW

**Comment by GeorgeS2019** [comment]
@valkyrienyanko 

Please share which Godot4 version u are able to get it running.

It fails to run for me recently.

**Comment by valkyrienyanko** [comment]
`Godot_v4.1-rc3_mono_win64`

**Comment by GeorgeS2019** [comment]
Found the problem

The test projects not sync with the GodotXunit and GodotXunitAPI

**Comment by GeorgeS2019** [comment]
Thx for cleaning UP!

**Comment by valkyrienyanko** [comment]
I'm going to close this PR, feel free to re-open if you want to merge.

**Pull request closed without merging**
